environment: &environment
  runs-on: ubuntu-latest
  strategy:
    matrix:
      node-version: [8, 10, 12]

name: CI

on: [push]

jobs:
  lint:
    <<: *environment
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install and lint
      run: |
        npm ci
        npm run lint
      env:
        CI: true
  other:
    <<: *environment
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: something
      run: |
        npm ci
        npm run lint
      env:
        CI: true