name: CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: npm install and lint
      run: |
        npm ci
        npm run lint
      env:
        CI: true